export const AUDIT_ACTIONS = [
  'person_created',
  'person_activated',
  'permission_preview_generated',
  'permission_confirmed',
  'permission_changed',
  'permission_revoked',
  'permission_suspended_inactivity',
  'first_contact_received',
  'owner_confirmed_identity',
  'transaction_created',
  'transaction_corrected',
  'transaction_cancelled',
  'classification_suggested',
  'reminder_scheduled',
  'boleto_parsed',
  'audio_transcribed',
  'rule_learned',
  'rule_promoted',
  'rule_demoted',
  'rule_banned',
  'fact_saved',
  'memory_recalled',
  'reflection_completed',
  'dual_approval_requested',
  'dual_approval_granted',
  'dual_approval_denied',
  'dual_approval_timeout',
  'dual_approval_executed',
  'audit_mode_activated',
  'audit_mode_deactivated',
  'audit_mode_deactivated_auto',
  'emergency_lockdown_activated',
  'emergency_lockdown_lifted',
  'unauthorized_access_attempt',
  'rate_limit_exceeded',
  'unknown_number_message_received',
  'group_message_ignored',
  'duplicate_message_dropped',
  'auto_blocked_anomalous_volume',
  'system_started',
  'system_stopped',
  'config_loaded',
  'backup_completed',
  'backup_failed',
  'restore_test_passed',
  'restore_test_failed',
  'whatsapp_connected',
  'whatsapp_disconnected',
  'llm_circuit_opened',
  'llm_circuit_closed',
  'dashboard_session_started',
  'dashboard_session_ended',
  'dlq_job_added',
  'dlq_job_resolved',
  'pending_resolved',
  'pending_cancelled',
  'pending_expired',
  'balance_queried',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const ACTION_KEYS = [
  'read_balance',
  'read_transactions',
  'read_reports',
  'read_recurrences',
  'read_pending_questions',
  'read_audit',
  'create_transaction',
  'correct_transaction',
  'cancel_transaction',
  'schedule_reminder',
  'create_pessoa',
  'update_pessoa',
  'change_permission',
  'create_conta_bancaria',
  'update_conta_bancaria',
  'create_contraparte',
  'update_contraparte',
  'send_proactive_message',
  'activate_audit_mode',
  'deactivate_audit_mode',
  'emergency_lockdown',
  'emergency_unlock',
  'mark_rule_firm',
  'ban_rule',
] as const;

export type ActionKey = (typeof ACTION_KEYS)[number];
