-- 063: agent_memories_cleanup_backup — quarantine table for reflection cleanup
-- (issue #260, PR #276, Codex review iter 2 — BLOCK on hard-delete without backup).
--
-- The reflection-memory-cleanup script (`scripts/reflection-memory-cleanup.ts`)
-- hard-deletes rows from `agent_memories` that landed in the polluted
-- `(tenant_id='default', agent_id='default')` bucket due to the pre-#251
-- reflection batch worker. The 2nd Codex review iteration on PR #276
-- identified the absence of an undo path as a CRITICAL blocker:
--
--   "Hard delete SEM backup nem undo (...) run errado ou mudança de escopo
--    concorrente NÃO pode ser revertido nem limitado ao sample confirmado."
--
-- Resolution: every `--execute` run now snapshots in-scope rows into THIS
-- quarantine table BEFORE the DELETE statement, inside the same transaction.
-- The original `id` and ALL of `agent_memories`' user-data columns are
-- preserved so an operator can `--undo=<run_id>` to restore the rows
-- byte-identical to their pre-delete state. The script also reads from
-- this table to FREEZE the candidate ID set between dry-run and execute,
-- preventing the race window flagged by Codex blocker #6 (predicate
-- re-evaluated per batch).
--
-- Shape:
--   - `cleanup_run_id` is the UUID that ties together every backed-up row
--     and the matching `admin_audit_log` entry (action=
--     'reflection_memory_cleanup'). It is generated client-side by the
--     script before the first INSERT and persisted in the audit
--     `change_summary.cleanup_run_id`.
--   - `original_id` is the `agent_memories.id` of the deleted row,
--     preserved so `--undo` can re-insert with the SAME primary key (we
--     do NOT keep an FK to `agent_memories` because the row will be
--     gone right after the snapshot; the column is purely a forensic
--     marker).
--   - The user-data columns (`tenant_id`, `agent_id`, `conteudo`,
--     `embedding`, `tipo`, `escopo`, `metadata`, `ref_tabela`, `ref_id`,
--     `original_created_at`) are full copies. We do NOT copy `id` into
--     a column named `id` because BIGSERIAL `id` is the quarantine
--     table's own PK; the original UUID goes into `original_id`.
--   - `deleted_at` is the wall-clock time the row was quarantined (NOT
--     the source row's `created_at`).
--   - `deleted_by` is the operator identity recorded in the audit row
--     (same `executed_by_user` value).
--   - `restored_at` is non-null after a successful `--undo`. The script
--     stamps it under the SAME `cleanup_run_id`, so re-running `--undo`
--     for an already-restored run is a no-op (idempotent).
--
-- Retention: this table is APPEND-ONLY for the cleanup window. Operators
-- can manually `TRUNCATE` it after a validation period (the rollback
-- runbook on issue #260 suggests 30 days), but the script itself never
-- deletes from this table — it only INSERTs (snapshot) and UPDATEs
-- (mark `restored_at`).
--
-- Indices:
--   - `(cleanup_run_id)` is the primary lookup pattern for `--undo` and
--     for joining to the audit row.
--   - `(tenant_id, agent_id)` matches the access pattern of an operator
--     auditing what was removed from a specific bucket.
--   - `(deleted_at)` supports retention queries ("what was quarantined
--     more than 30 days ago and can be purged?").

CREATE TABLE IF NOT EXISTS agent_memories_cleanup_backup (
  id BIGSERIAL PRIMARY KEY,
  cleanup_run_id UUID NOT NULL,
  original_id UUID NOT NULL,
  tenant_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  conteudo TEXT NOT NULL,
  embedding TEXT,
  tipo TEXT NOT NULL,
  escopo TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  ref_tabela TEXT,
  ref_id UUID,
  original_created_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_by TEXT NOT NULL,
  restored_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS agent_memories_cleanup_backup_run_idx
  ON agent_memories_cleanup_backup(cleanup_run_id);
CREATE INDEX IF NOT EXISTS agent_memories_cleanup_backup_bucket_idx
  ON agent_memories_cleanup_backup(tenant_id, agent_id);
CREATE INDEX IF NOT EXISTS agent_memories_cleanup_backup_deleted_at_idx
  ON agent_memories_cleanup_backup(deleted_at);

COMMENT ON TABLE agent_memories_cleanup_backup IS
  'Quarantine snapshot of agent_memories rows removed by scripts/reflection-memory-cleanup.ts (#260). Append-only; backed up rows are restorable via --undo=<cleanup_run_id>. Operators can TRUNCATE after retention window (see issue #260 runbook).';
COMMENT ON COLUMN agent_memories_cleanup_backup.cleanup_run_id IS
  'Per-run UUID generated by the script. Same value is stored in admin_audit_log.change_summary.cleanup_run_id to join the two.';
COMMENT ON COLUMN agent_memories_cleanup_backup.original_id IS
  'The agent_memories.id value at delete time. NOT an FK because the source row is gone. --undo re-INSERTs into agent_memories with this id.';
COMMENT ON COLUMN agent_memories_cleanup_backup.restored_at IS
  'Non-null after --undo successfully re-inserts this row into agent_memories. UPDATE-only column; the script never DELETEs from this table.';
