import { unlink } from 'node:fs/promises';
import { logger } from '@/lib/logger.js';

/**
 * Removes a temporary PDF file generated by `generate_report` after the
 * outbound document has been sent (or attempted). Failures are logged and
 * swallowed — the boot sweeper acts as the safety net for crash-mid-send.
 */
export async function cleanupPDF(path: string): Promise<void> {
  await unlink(path).catch((err) => {
    logger.warn({ err, path }, 'pdf.unlink_failed_will_be_swept');
  });
}
