/**
 * Integration test for `globalSettingsRepo.updateAtomic` (migration 062).
 *
 * Codex Adversarial Review on PR #188 (issue #183), round 1, [medium]:
 *   The first port of the founder LLM model switch read current values
 *   OUTSIDE the tx, then conditional-skipped writes based on that stale
 *   snapshot, then audited `after={input.main, input.fast}`. Two concurrent
 *   founders could land:
 *     - tx A reads before=(X,X), schedules write fast=Y.
 *     - tx B reads before=(X,X), schedules write main=Z.
 *     - Both commit. DB ends at (Z,Y), but audit row A claims (X,X)→(X,Y)
 *       and audit row B claims (X,X)→(Z,X). Neither matches what the DB
 *       actually holds. Forensic trail corrupted.
 *
 * Fix: `updateAtomic` reads each key's current value INSIDE the tx under
 * `SELECT ... FOR UPDATE` on the row's PK, then UPSERTs, then audits. The
 * audit row reflects the REAL pre-lock value and the REAL post-upsert
 * value, even when two founders run in parallel.
 *
 * This test reproduces that scenario against a real Postgres (gated on
 * TEST_DB_URL like the other integration tests in this file).
 *
 * Skipped without TEST_DB_URL (matches the gate used in
 * `issue-166-propose-version-race.spec.ts`).
 */
import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import pg from 'pg';

const SHOULD_RUN =
  !!process.env.TEST_DB_URL &&
  process.env.DATABASE_URL === process.env.TEST_DB_URL;
const d = SHOULD_RUN ? describe : describe.skip;

// All audit rows generated by this test land under this tenant so afterAll
// can clean up without affecting other test data.
const T = 'issue183-tenant';
const ACTOR_A = 'issue183-founder-a@example.com';
const ACTOR_B = 'issue183-founder-b@example.com';

let pool: pg.Pool;

async function resetGlobalSettings(): Promise<void> {
  const c = await pool.connect();
  try {
    // global_settings is process-wide (no tenant FK) — purge by key prefix.
    await c.query(`DELETE FROM global_settings WHERE key LIKE 'llm.model.%'`);
    await c.query(
      `DELETE FROM admin_audit_log WHERE tenant_id = $1 AND action IN ('llm_model_changed', 'global_settings_update')`,
      [T],
    );
  } finally {
    c.release();
  }
}

if (SHOULD_RUN) {
  beforeAll(async () => {
    pool = new pg.Pool({ connectionString: process.env.TEST_DB_URL });
    // Make sure a tenant row exists for the audit FK (if one is added in
    // future). Currently admin_audit_log has no FK to tenants, so this is
    // belt-and-suspenders.
    const c = await pool.connect();
    try {
      await c.query(
        `INSERT INTO tenants(id, nome) VALUES ($1, 'Issue 183 Tenant') ON CONFLICT (id) DO NOTHING`,
        [T],
      );
    } finally {
      c.release();
    }
  });

  afterAll(async () => {
    const c = await pool.connect();
    try {
      await c.query(`DELETE FROM global_settings WHERE key LIKE 'llm.model.%'`);
      await c.query(
        `DELETE FROM admin_audit_log WHERE tenant_id = $1`,
        [T],
      );
      await c.query(`DELETE FROM tenants WHERE id = $1`, [T]);
    } finally {
      c.release();
      await pool.end();
    }
  });

  beforeEach(async () => {
    await resetGlobalSettings();
  });
}

d('globalSettingsRepo.getByKey + updateAtomic (real DB)', () => {
  it('getByKey returns null when the row does not exist', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');
    const r = await globalSettingsRepo.getByKey('llm.model.main');
    expect(r).toBeNull();
  });

  it('updateAtomic happy path: writes UPSERT + audit row, reports before/after', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    const res = await globalSettingsRepo.updateAtomic({
      keys: [
        { key: 'llm.model.main', value: { model: 'openai/gpt-5' } },
        { key: 'llm.model.fast', value: { model: 'x-ai/grok-4.1-fast' } },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'happy path' },
      },
    });
    expect(res.ok).toBe(true);
    if (!res.ok) throw new Error('unreachable');
    expect(res.before).toEqual({
      'llm.model.main': null,
      'llm.model.fast': null,
    });
    expect(res.after).toEqual({
      'llm.model.main': { model: 'openai/gpt-5' },
      'llm.model.fast': { model: 'x-ai/grok-4.1-fast' },
    });

    // The rows actually landed in global_settings.
    const c = await pool.connect();
    try {
      const r = await c.query<{ key: string; value: { model: string } }>(
        `SELECT key, value FROM global_settings WHERE key LIKE 'llm.model.%' ORDER BY key`,
      );
      expect(r.rows.length).toBe(2);
      expect(r.rows[0]!.key).toBe('llm.model.fast');
      expect(r.rows[0]!.value.model).toBe('x-ai/grok-4.1-fast');
      expect(r.rows[1]!.key).toBe('llm.model.main');
      expect(r.rows[1]!.value.model).toBe('openai/gpt-5');

      // Audit row landed too.
      const a = await c.query<{ count: string }>(
        `SELECT COUNT(*)::text AS count FROM admin_audit_log
          WHERE tenant_id = $1 AND action = 'llm_model_changed'`,
        [T],
      );
      expect(a.rows[0]!.count).toBe('1');
    } finally {
      c.release();
    }
  });

  it('updateAtomic returns no_changes when both keys already match', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Seed both rows.
    await globalSettingsRepo.updateAtomic({
      keys: [
        { key: 'llm.model.main', value: { model: 'openai/gpt-5' } },
        { key: 'llm.model.fast', value: { model: 'openai/gpt-5' } },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'seed' },
      },
    });

    // Run again with the same values.
    const res = await globalSettingsRepo.updateAtomic({
      keys: [
        { key: 'llm.model.main', value: { model: 'openai/gpt-5' } },
        { key: 'llm.model.fast', value: { model: 'openai/gpt-5' } },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'no-op renew' },
      },
    });
    expect(res.ok).toBe(false);
    if (res.ok) throw new Error('unreachable');
    expect(res.reason).toBe('no_changes');

    // Exactly one audit row (from the seed). No second row from the no-op.
    const c = await pool.connect();
    try {
      const a = await c.query<{ count: string }>(
        `SELECT COUNT(*)::text AS count FROM admin_audit_log
          WHERE tenant_id = $1 AND action = 'llm_model_changed'`,
        [T],
      );
      expect(a.rows[0]!.count).toBe('1');
    } finally {
      c.release();
    }
  });

  /**
   * Codex round 1 regression: two founders updating different sides of
   * the LLM model split, concurrently. Pre-fix the audit row could claim
   * an `after` value that didn't match what landed in the DB, because
   * the conditional-skip logic ran against a stale pre-tx snapshot.
   *
   * Post-fix: each tx reads each key under SELECT FOR UPDATE, so the
   * second tx sees the first tx's commit as its `before`. The audit
   * rows for tx1 and tx2 together must form a linear lineage from the
   * initial state to the final state.
   */
  it('concurrency: two founders updating overlapping keys → audit lineage matches DB final state', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Seed initial state so both txs have a non-null `before`.
    await globalSettingsRepo.updateAtomic({
      keys: [
        { key: 'llm.model.main', value: { model: 'anthropic/claude-sonnet-4.6' } },
        { key: 'llm.model.fast', value: { model: 'anthropic/claude-haiku-4.5' } },
      ],
      audit: {
        tenant_id: T,
        actor_id: 'seed',
        actor_role: 'system',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'seed' },
      },
    });

    // Founder A wants to flip BOTH sides to openai/gpt-5.
    // Founder B wants to flip BOTH sides to x-ai/grok-4.1-fast.
    // They run concurrently. The repo's FOR UPDATE lock must serialize
    // them. Final DB state must equal whichever tx committed second, and
    // BOTH audit rows must be present with chained before→after values.
    const [resA, resB] = await Promise.all([
      globalSettingsRepo.updateAtomic({
        keys: [
          { key: 'llm.model.main', value: { model: 'openai/gpt-5' } },
          { key: 'llm.model.fast', value: { model: 'openai/gpt-5' } },
        ],
        audit: {
          tenant_id: T,
          actor_id: ACTOR_A,
          actor_role: 'founder',
          action: 'llm_model_changed',
          resource_type: 'llm_settings',
          meta: { comment: 'founder A flips both' },
        },
      }),
      globalSettingsRepo.updateAtomic({
        keys: [
          { key: 'llm.model.main', value: { model: 'x-ai/grok-4.1-fast' } },
          { key: 'llm.model.fast', value: { model: 'x-ai/grok-4.1-fast' } },
        ],
        audit: {
          tenant_id: T,
          actor_id: ACTOR_B,
          actor_role: 'founder',
          action: 'llm_model_changed',
          resource_type: 'llm_settings',
          meta: { comment: 'founder B flips both' },
        },
      }),
    ]);

    expect(resA.ok).toBe(true);
    expect(resB.ok).toBe(true);
    if (!resA.ok || !resB.ok) throw new Error('unreachable');

    // Final DB state.
    const c = await pool.connect();
    let finalMain: string;
    let finalFast: string;
    let auditByActor: Map<string, {
      before: Record<string, unknown>;
      after: Record<string, unknown>;
    }>;
    try {
      const rowsRes = await c.query<{ key: string; value: { model: string } }>(
        `SELECT key, value FROM global_settings WHERE key LIKE 'llm.model.%' ORDER BY key`,
      );
      const byKey = new Map(rowsRes.rows.map((r) => [r.key, r.value.model]));
      finalMain = byKey.get('llm.model.main')!;
      finalFast = byKey.get('llm.model.fast')!;

      const auditRes = await c.query<{
        actor_id: string;
        change_summary: {
          before: Record<string, unknown>;
          after: Record<string, unknown>;
        };
      }>(
        `SELECT actor_id, change_summary FROM admin_audit_log
          WHERE tenant_id = $1
            AND action = 'llm_model_changed'
            AND actor_id = ANY($2::text[])
          ORDER BY id`,
        [T, [ACTOR_A, ACTOR_B]],
      );
      auditByActor = new Map(
        auditRes.rows.map((r) => [
          r.actor_id,
          { before: r.change_summary.before, after: r.change_summary.after },
        ]),
      );
    } finally {
      c.release();
    }

    // Both founders flipped main+fast to the same value, so final state is
    // whichever ran second.
    expect(finalMain).toBe(finalFast);
    expect(['openai/gpt-5', 'x-ai/grok-4.1-fast']).toContain(finalMain);

    // CRITICAL — Codex regression: each audit row's after MUST match what
    // its tx committed under the lock, and the two audit rows together
    // must form a chain (the second one's `before` equals the first one's
    // `after`). Pre-fix this could fail because the stale pre-tx snapshot
    // meant `before` reflected the seed and `after` reflected only the
    // caller's input, never observing the other founder's commit.
    const aRow = auditByActor.get(ACTOR_A)!;
    const bRow = auditByActor.get(ACTOR_B)!;
    expect(aRow).toBeDefined();
    expect(bRow).toBeDefined();

    // Identify which tx committed first by tracing the chain. The first
    // tx's `before` must be the seed values. The second tx's `before`
    // must equal the first tx's `after`. The second tx's `after` must
    // equal the final DB state.
    const seed = {
      'llm.model.main': { model: 'anthropic/claude-sonnet-4.6' },
      'llm.model.fast': { model: 'anthropic/claude-haiku-4.5' },
    };
    const finalAfter = {
      'llm.model.main': { model: finalMain },
      'llm.model.fast': { model: finalFast },
    };

    const aIsFirst = JSON.stringify(aRow.before) === JSON.stringify(seed);
    const bIsFirst = JSON.stringify(bRow.before) === JSON.stringify(seed);
    expect(aIsFirst !== bIsFirst).toBe(true); // exactly one is first

    const first = aIsFirst ? aRow : bRow;
    const second = aIsFirst ? bRow : aRow;

    expect(first.before).toEqual(seed);
    // Second's before MUST equal first's after — this is the invariant
    // that the SELECT FOR UPDATE guarantees and the stale-read bug broke.
    expect(second.before).toEqual(first.after);
    expect(second.after).toEqual(finalAfter);
  });

  /**
   * Audit-insert failure rolls back ALL upserts in the same tx. This is
   * the same invariant `tenantsRepo.updateStatusAtomic` and
   * `operationalProfileVersionsRepo.proposeAndAuditAtomic` enforce — a
   * fatal-after-write here would leave the model facts permanently
   * changed with no forensic record.
   *
   * We can't easily trigger a real audit-insert failure in integration
   * (the admin_audit_log table has no fragile constraint we can violate
   * cheaply), so we exercise the path indirectly: a duplicate primary
   * key on a manually-pre-inserted audit row triggers a NOT NULL
   * violation that aborts the tx. The expected outcome is that the
   * global_settings rows are unchanged from their pre-tx state.
   */
  it('audit failure rolls back the upserts (atomicity invariant)', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Seed an initial value so we can prove rollback restores it.
    await globalSettingsRepo.updateAtomic({
      keys: [{ key: 'llm.model.main', value: { model: 'seed-model' } }],
      audit: {
        tenant_id: T,
        actor_id: 'seed',
        actor_role: 'system',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
      },
    });

    // Spy on the audit insert path: monkeypatching is awkward, so we
    // trigger a constraint violation indirectly by feeding the audit
    // helper a non-string action (the schema requires text NOT NULL).
    // The whole tx must abort.
    await expect(
      globalSettingsRepo.updateAtomic({
        keys: [{ key: 'llm.model.main', value: { model: 'attempted-write' } }],
        audit: {
          tenant_id: T,
          actor_id: ACTOR_A,
          actor_role: 'founder',
          // @ts-expect-error — intentionally invalid for the test.
          action: null,
          resource_type: 'llm_settings',
        },
      }),
    ).rejects.toThrow();

    // global_settings must STILL hold the seed value — the upsert that
    // ran before the audit insert was rolled back when the audit failed.
    const c = await pool.connect();
    try {
      const r = await c.query<{ value: { model: string } }>(
        `SELECT value FROM global_settings WHERE key = 'llm.model.main'`,
      );
      expect(r.rows[0]!.value.model).toBe('seed-model');
    } finally {
      c.release();
    }
  });
});
