/**
 * Integration test for `globalSettingsRepo.updateAtomic` (migration 062).
 *
 * Codex Adversarial Review on PR #188 (issue #183), round 1, [medium]:
 *   The first port of the founder LLM model switch read current values
 *   OUTSIDE the tx, then conditional-skipped writes based on that stale
 *   snapshot, then audited `after={input.main, input.fast}`. Two concurrent
 *   founders could land:
 *     - tx A reads before=(X,X), schedules write fast=Y.
 *     - tx B reads before=(X,X), schedules write main=Z.
 *     - Both commit. DB ends at (Z,Y), but audit row A claims (X,X)→(X,Y)
 *       and audit row B claims (X,X)→(Z,X). Neither matches what the DB
 *       actually holds. Forensic trail corrupted.
 *
 * Fix: `updateAtomic` reads each key's current value INSIDE the tx under
 * `SELECT ... FOR UPDATE` on the row's PK, then UPSERTs, then audits. The
 * audit row reflects the REAL pre-lock value and the REAL post-upsert
 * value, even when two founders run in parallel.
 *
 * This test reproduces that scenario against a real Postgres (gated on
 * TEST_DB_URL like the other integration tests in this file).
 *
 * Skipped without TEST_DB_URL (matches the gate used in
 * `issue-166-propose-version-race.spec.ts`).
 */
import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import pg from 'pg';

const SHOULD_RUN =
  !!process.env.TEST_DB_URL &&
  process.env.DATABASE_URL === process.env.TEST_DB_URL;
const d = SHOULD_RUN ? describe : describe.skip;

// All audit rows generated by this test land under this tenant so afterAll
// can clean up without affecting other test data.
const T = 'issue183-tenant';
const ACTOR_A = 'issue183-founder-a@example.com';
const ACTOR_B = 'issue183-founder-b@example.com';

let pool: pg.Pool;

async function resetGlobalSettings(): Promise<void> {
  const c = await pool.connect();
  try {
    // global_settings is process-wide (no tenant FK) — purge by key prefix.
    await c.query(`DELETE FROM global_settings WHERE key LIKE 'llm.model.%'`);
    await c.query(
      `DELETE FROM admin_audit_log WHERE tenant_id = $1 AND action IN ('llm_model_changed', 'global_settings_update')`,
      [T],
    );
  } finally {
    c.release();
  }
}

if (SHOULD_RUN) {
  beforeAll(async () => {
    pool = new pg.Pool({ connectionString: process.env.TEST_DB_URL });
    // Make sure a tenant row exists for the audit FK (if one is added in
    // future). Currently admin_audit_log has no FK to tenants, so this is
    // belt-and-suspenders.
    const c = await pool.connect();
    try {
      await c.query(
        `INSERT INTO tenants(id, nome) VALUES ($1, 'Issue 183 Tenant') ON CONFLICT (id) DO NOTHING`,
        [T],
      );
    } finally {
      c.release();
    }
  });

  afterAll(async () => {
    const c = await pool.connect();
    try {
      await c.query(`DELETE FROM global_settings WHERE key LIKE 'llm.model.%'`);
      await c.query(
        `DELETE FROM admin_audit_log WHERE tenant_id = $1`,
        [T],
      );
      await c.query(`DELETE FROM tenants WHERE id = $1`, [T]);
    } finally {
      c.release();
      await pool.end();
    }
  });

  beforeEach(async () => {
    await resetGlobalSettings();
  });
}

d('globalSettingsRepo.getByKey + updateAtomic (real DB)', () => {
  it('getByKey returns null when the row does not exist', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');
    const r = await globalSettingsRepo.getByKey('llm.model.main');
    expect(r).toBeNull();
  });

  it('updateAtomic happy path: writes UPSERT + audit row, reports before/after', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    const res = await globalSettingsRepo.updateAtomic({
      keys: [
        { key: 'llm.model.main', value: { model: 'openai/gpt-5' } },
        { key: 'llm.model.fast', value: { model: 'x-ai/grok-4.1-fast' } },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'happy path' },
      },
    });
    expect(res.ok).toBe(true);
    if (!res.ok) throw new Error('unreachable');
    expect(res.before).toEqual({
      'llm.model.main': null,
      'llm.model.fast': null,
    });
    expect(res.after).toEqual({
      'llm.model.main': { model: 'openai/gpt-5' },
      'llm.model.fast': { model: 'x-ai/grok-4.1-fast' },
    });

    // The rows actually landed in global_settings.
    const c = await pool.connect();
    try {
      const r = await c.query<{ key: string; value: { model: string } }>(
        `SELECT key, value FROM global_settings WHERE key LIKE 'llm.model.%' ORDER BY key`,
      );
      expect(r.rows.length).toBe(2);
      expect(r.rows[0]!.key).toBe('llm.model.fast');
      expect(r.rows[0]!.value.model).toBe('x-ai/grok-4.1-fast');
      expect(r.rows[1]!.key).toBe('llm.model.main');
      expect(r.rows[1]!.value.model).toBe('openai/gpt-5');

      // Audit row landed too.
      const a = await c.query<{ count: string }>(
        `SELECT COUNT(*)::text AS count FROM admin_audit_log
          WHERE tenant_id = $1 AND action = 'llm_model_changed'`,
        [T],
      );
      expect(a.rows[0]!.count).toBe('1');
    } finally {
      c.release();
    }
  });

  it('updateAtomic returns no_changes when both keys already match', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Seed both rows.
    await globalSettingsRepo.updateAtomic({
      keys: [
        { key: 'llm.model.main', value: { model: 'openai/gpt-5' } },
        { key: 'llm.model.fast', value: { model: 'openai/gpt-5' } },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'seed' },
      },
    });

    // Run again with the same values.
    const res = await globalSettingsRepo.updateAtomic({
      keys: [
        { key: 'llm.model.main', value: { model: 'openai/gpt-5' } },
        { key: 'llm.model.fast', value: { model: 'openai/gpt-5' } },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'no-op renew' },
      },
    });
    expect(res.ok).toBe(false);
    if (res.ok) throw new Error('unreachable');
    expect(res.reason).toBe('no_changes');

    // Exactly one audit row (from the seed). No second row from the no-op.
    const c = await pool.connect();
    try {
      const a = await c.query<{ count: string }>(
        `SELECT COUNT(*)::text AS count FROM admin_audit_log
          WHERE tenant_id = $1 AND action = 'llm_model_changed'`,
        [T],
      );
      expect(a.rows[0]!.count).toBe('1');
    } finally {
      c.release();
    }
  });

  /**
   * Codex round 1 regression: two founders updating different sides of
   * the LLM model split, concurrently. Pre-fix the audit row could claim
   * an `after` value that didn't match what landed in the DB, because
   * the conditional-skip logic ran against a stale pre-tx snapshot.
   *
   * Post-fix: each tx reads each key under SELECT FOR UPDATE, so the
   * second tx sees the first tx's commit as its `before`. The audit
   * rows for tx1 and tx2 together must form a linear lineage from the
   * initial state to the final state.
   */
  it('concurrency: two founders updating overlapping keys → audit lineage matches DB final state', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Seed initial state so both txs have a non-null `before`.
    await globalSettingsRepo.updateAtomic({
      keys: [
        { key: 'llm.model.main', value: { model: 'anthropic/claude-sonnet-4.6' } },
        { key: 'llm.model.fast', value: { model: 'anthropic/claude-haiku-4.5' } },
      ],
      audit: {
        tenant_id: T,
        actor_id: 'seed',
        actor_role: 'system',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'seed' },
      },
    });

    // Founder A wants to flip BOTH sides to openai/gpt-5.
    // Founder B wants to flip BOTH sides to x-ai/grok-4.1-fast.
    // They run concurrently. The repo's FOR UPDATE lock must serialize
    // them. Final DB state must equal whichever tx committed second, and
    // BOTH audit rows must be present with chained before→after values.
    const [resA, resB] = await Promise.all([
      globalSettingsRepo.updateAtomic({
        keys: [
          { key: 'llm.model.main', value: { model: 'openai/gpt-5' } },
          { key: 'llm.model.fast', value: { model: 'openai/gpt-5' } },
        ],
        audit: {
          tenant_id: T,
          actor_id: ACTOR_A,
          actor_role: 'founder',
          action: 'llm_model_changed',
          resource_type: 'llm_settings',
          meta: { comment: 'founder A flips both' },
        },
      }),
      globalSettingsRepo.updateAtomic({
        keys: [
          { key: 'llm.model.main', value: { model: 'x-ai/grok-4.1-fast' } },
          { key: 'llm.model.fast', value: { model: 'x-ai/grok-4.1-fast' } },
        ],
        audit: {
          tenant_id: T,
          actor_id: ACTOR_B,
          actor_role: 'founder',
          action: 'llm_model_changed',
          resource_type: 'llm_settings',
          meta: { comment: 'founder B flips both' },
        },
      }),
    ]);

    expect(resA.ok).toBe(true);
    expect(resB.ok).toBe(true);
    if (!resA.ok || !resB.ok) throw new Error('unreachable');

    // Final DB state.
    const c = await pool.connect();
    let finalMain: string;
    let finalFast: string;
    let auditByActor: Map<string, {
      before: Record<string, unknown>;
      after: Record<string, unknown>;
    }>;
    try {
      const rowsRes = await c.query<{ key: string; value: { model: string } }>(
        `SELECT key, value FROM global_settings WHERE key LIKE 'llm.model.%' ORDER BY key`,
      );
      const byKey = new Map(rowsRes.rows.map((r) => [r.key, r.value.model]));
      finalMain = byKey.get('llm.model.main')!;
      finalFast = byKey.get('llm.model.fast')!;

      const auditRes = await c.query<{
        actor_id: string;
        change_summary: {
          before: Record<string, unknown>;
          after: Record<string, unknown>;
        };
      }>(
        `SELECT actor_id, change_summary FROM admin_audit_log
          WHERE tenant_id = $1
            AND action = 'llm_model_changed'
            AND actor_id = ANY($2::text[])
          ORDER BY id`,
        [T, [ACTOR_A, ACTOR_B]],
      );
      auditByActor = new Map(
        auditRes.rows.map((r) => [
          r.actor_id,
          { before: r.change_summary.before, after: r.change_summary.after },
        ]),
      );
    } finally {
      c.release();
    }

    // Both founders flipped main+fast to the same value, so final state is
    // whichever ran second.
    expect(finalMain).toBe(finalFast);
    expect(['openai/gpt-5', 'x-ai/grok-4.1-fast']).toContain(finalMain);

    // CRITICAL — Codex regression: each audit row's after MUST match what
    // its tx committed under the lock, and the two audit rows together
    // must form a chain (the second one's `before` equals the first one's
    // `after`). Pre-fix this could fail because the stale pre-tx snapshot
    // meant `before` reflected the seed and `after` reflected only the
    // caller's input, never observing the other founder's commit.
    const aRow = auditByActor.get(ACTOR_A)!;
    const bRow = auditByActor.get(ACTOR_B)!;
    expect(aRow).toBeDefined();
    expect(bRow).toBeDefined();

    // Identify which tx committed first by tracing the chain. The first
    // tx's `before` must be the seed values. The second tx's `before`
    // must equal the first tx's `after`. The second tx's `after` must
    // equal the final DB state.
    const seed = {
      'llm.model.main': { model: 'anthropic/claude-sonnet-4.6' },
      'llm.model.fast': { model: 'anthropic/claude-haiku-4.5' },
    };
    const finalAfter = {
      'llm.model.main': { model: finalMain },
      'llm.model.fast': { model: finalFast },
    };

    // Codex round 3 on PR #188 [P3]: `jsonb` does NOT preserve object
    // key insertion order on round-trip through Postgres. The seed
    // literal puts `main` first; `updateAtomic` sorts keys before
    // locking and builds `before` in sorted order (`fast` first); so
    // a `JSON.stringify(...)` equality check could legitimately
    // mismatch despite identical contents. Use vitest's deep-equal
    // matchers (`toEqual`) — they walk object keys, not strings —
    // for ALL jsonb comparisons in this file.
    function deepEqual(a: unknown, b: unknown): boolean {
      // Tiny helper so the "which row is first" disambiguation below
      // matches the toEqual semantics used elsewhere in this file.
      return JSON.stringify(sortKeys(a)) === JSON.stringify(sortKeys(b));
    }
    function sortKeys(v: unknown): unknown {
      if (Array.isArray(v)) return v.map(sortKeys);
      if (v && typeof v === 'object') {
        const o: Record<string, unknown> = {};
        for (const k of Object.keys(v as object).sort()) {
          o[k] = sortKeys((v as Record<string, unknown>)[k]);
        }
        return o;
      }
      return v;
    }
    const aIsFirst = deepEqual(aRow.before, seed);
    const bIsFirst = deepEqual(bRow.before, seed);
    expect(aIsFirst !== bIsFirst).toBe(true); // exactly one is first

    const first = aIsFirst ? aRow : bRow;
    const second = aIsFirst ? bRow : aRow;

    expect(first.before).toEqual(seed);
    // Second's before MUST equal first's after — this is the invariant
    // that the SELECT FOR UPDATE guarantees and the stale-read bug broke.
    expect(second.before).toEqual(first.after);
    expect(second.after).toEqual(finalAfter);
  });

  /**
   * Audit-insert failure rolls back ALL upserts in the same tx. This is
   * the same invariant `tenantsRepo.updateStatusAtomic` and
   * `operationalProfileVersionsRepo.proposeAndAuditAtomic` enforce — a
   * fatal-after-write here would leave the model facts permanently
   * changed with no forensic record.
   *
   * We can't easily trigger a real audit-insert failure in integration
   * (the admin_audit_log table has no fragile constraint we can violate
   * cheaply), so we exercise the path indirectly: a duplicate primary
   * key on a manually-pre-inserted audit row triggers a NOT NULL
   * violation that aborts the tx. The expected outcome is that the
   * global_settings rows are unchanged from their pre-tx state.
   */
  it('audit failure rolls back the upserts (atomicity invariant)', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Seed an initial value so we can prove rollback restores it.
    await globalSettingsRepo.updateAtomic({
      keys: [{ key: 'llm.model.main', value: { model: 'seed-model' } }],
      audit: {
        tenant_id: T,
        actor_id: 'seed',
        actor_role: 'system',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
      },
    });

    // Spy on the audit insert path: monkeypatching is awkward, so we
    // trigger a constraint violation indirectly by feeding the audit
    // helper a non-string action (the schema requires text NOT NULL).
    // The whole tx must abort.
    await expect(
      globalSettingsRepo.updateAtomic({
        keys: [{ key: 'llm.model.main', value: { model: 'attempted-write' } }],
        audit: {
          tenant_id: T,
          actor_id: ACTOR_A,
          actor_role: 'founder',
          // @ts-expect-error — intentionally invalid for the test.
          action: null,
          resource_type: 'llm_settings',
        },
      }),
    ).rejects.toThrow();

    // global_settings must STILL hold the seed value — the upsert that
    // ran before the audit insert was rolled back when the audit failed.
    const c = await pool.connect();
    try {
      const r = await c.query<{ value: { model: string } }>(
        `SELECT value FROM global_settings WHERE key = 'llm.model.main'`,
      );
      expect(r.rows[0]!.value.model).toBe('seed-model');
    } finally {
      c.release();
    }
  });

  /**
   * Codex round 3 on PR #188 [P2]: optimistic concurrency. The repo
   * accepts an optional `expected` per key; if the locked value doesn't
   * match, the helper returns reason='optimistic_conflict' and writes
   * NOTHING (no upsert, no audit row). This guards against two
   * founders loading the page from the same snapshot — Founder A
   * changes `main`, Founder B changes ONLY `fast` but submits the
   * stale `main` along with it. Without the check, B's stale `main`
   * silently reverts A's commit.
   */
  it('optimistic conflict: expected mismatch aborts the tx with no writes', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Seed the current state. Both founders observe this.
    await globalSettingsRepo.updateAtomic({
      keys: [
        { key: 'llm.model.main', value: { model: 'anthropic/claude-sonnet-4.6' } },
        { key: 'llm.model.fast', value: { model: 'anthropic/claude-haiku-4.5' } },
      ],
      audit: {
        tenant_id: T,
        actor_id: 'seed',
        actor_role: 'system',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'seed' },
      },
    });

    // Founder A wins the race: changes main to openai/gpt-5.
    await globalSettingsRepo.updateAtomic({
      keys: [
        {
          key: 'llm.model.main',
          value: { model: 'openai/gpt-5' },
          expected: { model: 'anthropic/claude-sonnet-4.6' },
        },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'founder A wins' },
      },
    });

    // Founder B submits a stale snapshot — expected_main still points
    // to the seed value, but the DB now holds openai/gpt-5. The repo
    // must refuse the write.
    const res = await globalSettingsRepo.updateAtomic({
      keys: [
        {
          key: 'llm.model.main',
          // B sends back the stale main from page load (unchanged on
          // B's side). Without the check, this would NOT trigger a
          // "no_changes" because it differs from current, but it WOULD
          // overwrite the openai/gpt-5 commit with the stale value —
          // exactly the reverted-A bug. The `expected` here is the
          // stale `anthropic/claude-sonnet-4.6` B observed at page
          // load, NOT the actual current `openai/gpt-5`.
          value: { model: 'anthropic/claude-sonnet-4.6' },
          expected: { model: 'anthropic/claude-sonnet-4.6' },
        },
        {
          key: 'llm.model.fast',
          value: { model: 'x-ai/grok-4.1-fast' }, // B's actual change
          expected: { model: 'anthropic/claude-haiku-4.5' },
        },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_B,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'founder B with stale snapshot' },
      },
    });

    expect(res.ok).toBe(false);
    if (res.ok) throw new Error('unreachable');
    expect(res.reason).toBe('optimistic_conflict');
    if (res.reason !== 'optimistic_conflict') throw new Error('unreachable');
    expect(res.key).toBe('llm.model.main');
    expect(res.expected).toEqual({ model: 'anthropic/claude-sonnet-4.6' });
    expect(res.current).toEqual({ model: 'openai/gpt-5' });

    // DB state unchanged: A's commit still stands. No audit row from
    // B's failed attempt (audit only fires after successful upsert).
    const c = await pool.connect();
    try {
      const main = await c.query<{ value: { model: string } }>(
        `SELECT value FROM global_settings WHERE key = 'llm.model.main'`,
      );
      expect(main.rows[0]!.value).toEqual({ model: 'openai/gpt-5' });

      const fast = await c.query<{ value: { model: string } }>(
        `SELECT value FROM global_settings WHERE key = 'llm.model.fast'`,
      );
      // fast remains at seed because B's whole tx aborted.
      expect(fast.rows[0]!.value).toEqual({
        model: 'anthropic/claude-haiku-4.5',
      });

      // Audit count: 1 (seed) + 1 (A) = 2. Nothing from B.
      const audit = await c.query<{ count: string }>(
        `SELECT COUNT(*)::text AS count FROM admin_audit_log
          WHERE tenant_id = $1 AND action = 'llm_model_changed'`,
        [T],
      );
      expect(audit.rows[0]!.count).toBe('2');
    } finally {
      c.release();
    }
  });

  it('optimistic conflict: expected matches → upsert proceeds normally', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Seed.
    await globalSettingsRepo.updateAtomic({
      keys: [{ key: 'llm.model.main', value: { model: 'seed' } }],
      audit: {
        tenant_id: T,
        actor_id: 'seed',
        actor_role: 'system',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
      },
    });

    // Update with correct expected → proceeds.
    const res = await globalSettingsRepo.updateAtomic({
      keys: [
        {
          key: 'llm.model.main',
          value: { model: 'after' },
          expected: { model: 'seed' },
        },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
      },
    });
    expect(res.ok).toBe(true);
    if (!res.ok) throw new Error('unreachable');
    expect(res.after).toEqual({ 'llm.model.main': { model: 'after' } });
  });

  /**
   * Codex round 4 on PR #188 [high]: fresh-install path. When
   * `global_settings` is empty, the admin UI must be able to apply the
   * first update with `expected: null` ("I observed no row"). The
   * helper inserts the placeholder JSON null, takes the FOR UPDATE
   * lock, sees `lockedValue === null`, compares `null === null`, and
   * proceeds. Previously this loop went the other way — the UI sent
   * the env default as expected, the helper wrapped it in {model:
   * <env-default>}, locked value was null, compare failed, every
   * fresh install was stuck.
   */
  it('fresh install: expected=null + empty global_settings → first update succeeds', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Confirm baseline: no row exists.
    const baseline = await globalSettingsRepo.getByKey('llm.model.main');
    expect(baseline).toBeNull();

    // First update with expected: null. The pre-round-4 helper would
    // wrap this in {model: <env-default>} (or similar) and CONFLICT
    // against the placeholder JSON null; round-4 propagates null
    // through and the comparison succeeds.
    const res = await globalSettingsRepo.updateAtomic({
      keys: [
        {
          key: 'llm.model.main',
          value: { model: 'openai/gpt-5' },
          expected: null,
        },
        {
          key: 'llm.model.fast',
          value: { model: 'x-ai/grok-4.1-fast' },
          expected: null,
        },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'first ever update on a fresh DB' },
      },
    });

    expect(res.ok).toBe(true);
    if (!res.ok) throw new Error('unreachable');
    expect(res.after).toEqual({
      'llm.model.main': { model: 'openai/gpt-5' },
      'llm.model.fast': { model: 'x-ai/grok-4.1-fast' },
    });

    // And both rows actually landed.
    const main = await globalSettingsRepo.getByKey('llm.model.main');
    const fast = await globalSettingsRepo.getByKey('llm.model.fast');
    expect(main?.value).toEqual({ model: 'openai/gpt-5' });
    expect(fast?.value).toEqual({ model: 'x-ai/grok-4.1-fast' });
  });

  /**
   * Codex round 4 [high]: the OTHER side of the null match — if
   * expected=null but a real row already exists, the compare correctly
   * fires CONFLICT. This guards against a stale tab from before the
   * first update.
   */
  it('expected=null but row exists → optimistic_conflict (not silent overwrite)', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Seed a real value.
    await globalSettingsRepo.updateAtomic({
      keys: [{ key: 'llm.model.main', value: { model: 'someone-already-wrote' } }],
      audit: {
        tenant_id: T,
        actor_id: 'seed',
        actor_role: 'system',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
      },
    });

    // Stale tab from before that write submits expected: null.
    const res = await globalSettingsRepo.updateAtomic({
      keys: [
        {
          key: 'llm.model.main',
          value: { model: 'stale-tab-write' },
          expected: null,
        },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
        meta: { comment: 'stale tab, should NOT overwrite' },
      },
    });

    expect(res.ok).toBe(false);
    if (res.ok) throw new Error('unreachable');
    expect(res.reason).toBe('optimistic_conflict');
    if (res.reason !== 'optimistic_conflict') throw new Error('unreachable');
    expect(res.expected).toBeNull();
    expect(res.current).toEqual({ model: 'someone-already-wrote' });

    // DB state unchanged.
    const main = await globalSettingsRepo.getByKey('llm.model.main');
    expect(main?.value).toEqual({ model: 'someone-already-wrote' });
  });

  /**
   * Codex round 5 on PR #188 [high]: round-5 writes through the helper
   * stamp `{ model, provider }` on each global_settings row. The
   * repo's `updateAtomic` now uses a "key-subset" compare semantic so
   * an expected token observed in the pre-round-5 shape (just
   * `{ model }`) still matches a round-5 row (`{ model, provider }`).
   * This protects the optimistic-conflict path from false positives
   * during the rolling deploy between this PR and the migration
   * stamping `provider` on existing rows.
   */
  it('round 5: subset-compare lets {model} expected match {model, provider} locked', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    // Seed under the round-5 shape (model + provider).
    await globalSettingsRepo.updateAtomic({
      keys: [
        {
          key: 'llm.model.main',
          value: { model: 'claude-sonnet-4-6', provider: 'anthropic' },
        },
      ],
      audit: {
        tenant_id: T,
        actor_id: 'seed',
        actor_role: 'system',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
      },
    });

    // Caller observed only the model (pre-round-5 shape). Subset
    // compare must accept it.
    const res = await globalSettingsRepo.updateAtomic({
      keys: [
        {
          key: 'llm.model.main',
          value: { model: 'claude-haiku-4-5', provider: 'anthropic' },
          expected: { model: 'claude-sonnet-4-6' },
        },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
      },
    });
    expect(res.ok).toBe(true);
    if (!res.ok) throw new Error('unreachable');
    expect(res.after).toEqual({
      'llm.model.main': { model: 'claude-haiku-4-5', provider: 'anthropic' },
    });
  });

  /**
   * Codex round 5 [high]: even with subset compare, a model-field
   * mismatch still produces optimistic_conflict. The guard is "expected
   * fields equal corresponding locked fields"; if expected.model
   * disagrees with locked.model, the lock catches it.
   */
  it('round 5: subset-compare still fires on real model mismatch', async () => {
    const { globalSettingsRepo } = await import('../../src/db/repositories.js');

    await globalSettingsRepo.updateAtomic({
      keys: [
        {
          key: 'llm.model.main',
          value: { model: 'claude-sonnet-4-6', provider: 'anthropic' },
        },
      ],
      audit: {
        tenant_id: T,
        actor_id: 'seed',
        actor_role: 'system',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
      },
    });

    const res = await globalSettingsRepo.updateAtomic({
      keys: [
        {
          key: 'llm.model.main',
          value: { model: 'claude-opus-4-7', provider: 'anthropic' },
          expected: { model: 'a-stale-snapshot' },
        },
      ],
      audit: {
        tenant_id: T,
        actor_id: ACTOR_A,
        actor_role: 'founder',
        action: 'llm_model_changed',
        resource_type: 'llm_settings',
      },
    });
    expect(res.ok).toBe(false);
    if (res.ok) throw new Error('unreachable');
    expect(res.reason).toBe('optimistic_conflict');
  });
});

/**
 * Codex round 5 on PR #188 [medium]: migration 062 down preserves
 * founder-driven `global_settings.llm.model.*` choices by backfilling
 * them into `agent_facts` (the legacy storage the pre-062 code reads)
 * before dropping the table. Without this, a rollback right after an
 * incident-time model switch silently loses the operator's pick.
 *
 * The test applies the down migration's SQL directly so we don't need
 * a migration runner: it's the same SQL the runner would emit.
 */
d('migration 062 down: backfill into agent_facts before DROP', () => {
  it('preserves llm.model.main/fast from global_settings into agent_facts', async () => {
    const c = await pool.connect();
    try {
      // Seed global_settings with the round-5 shape so the backfill
      // SQL has something to copy.
      await c.query(
        `INSERT INTO global_settings(key, value, updated_at, updated_by)
         VALUES ($1, $2, now(), 'test-seeder')
         ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()`,
        [
          'llm.model.main',
          JSON.stringify({ model: 'claude-sonnet-4-6', provider: 'anthropic' }),
        ],
      );
      await c.query(
        `INSERT INTO global_settings(key, value, updated_at, updated_by)
         VALUES ($1, $2, now(), 'test-seeder')
         ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()`,
        [
          'llm.model.fast',
          JSON.stringify({
            model: 'claude-haiku-4-5-20251001',
            provider: 'anthropic',
          }),
        ],
      );

      // Purge any pre-existing legacy rows so the test is deterministic.
      await c.query(
        `DELETE FROM agent_facts
         WHERE tenant_id = 'primary'
           AND agent_id = 'primary'
           AND escopo = 'global'
           AND chave IN ('llm.model.main', 'llm.model.fast')`,
      );

      // Run the same SQL the down migration ships. NOT the final DROP —
      // that would break other tests in this suite that need the table.
      await c.query(`
        INSERT INTO agent_facts (
          tenant_id, agent_id, escopo, chave, valor, confianca, fonte, updated_at
        )
        SELECT
          'primary','primary','global','llm.model.main',
          jsonb_build_object('model', value->>'model'),
          1.00,'configurado',updated_at
        FROM global_settings
        WHERE key = 'llm.model.main' AND value ? 'model'
        ON CONFLICT (tenant_id, agent_id, escopo, chave) DO UPDATE
          SET valor = EXCLUDED.valor,
              updated_at = EXCLUDED.updated_at,
              fonte = EXCLUDED.fonte;
      `);
      await c.query(`
        INSERT INTO agent_facts (
          tenant_id, agent_id, escopo, chave, valor, confianca, fonte, updated_at
        )
        SELECT
          'primary','primary','global','llm.model.fast',
          jsonb_build_object('model', value->>'model'),
          1.00,'configurado',updated_at
        FROM global_settings
        WHERE key = 'llm.model.fast' AND value ? 'model'
        ON CONFLICT (tenant_id, agent_id, escopo, chave) DO UPDATE
          SET valor = EXCLUDED.valor,
              updated_at = EXCLUDED.updated_at,
              fonte = EXCLUDED.fonte;
      `);

      const mainRow = await c.query<{ valor: { model: string } }>(
        `SELECT valor FROM agent_facts
         WHERE tenant_id='primary' AND agent_id='primary'
           AND escopo='global' AND chave='llm.model.main'`,
      );
      expect(mainRow.rows[0]!.valor).toEqual({ model: 'claude-sonnet-4-6' });

      const fastRow = await c.query<{ valor: { model: string } }>(
        `SELECT valor FROM agent_facts
         WHERE tenant_id='primary' AND agent_id='primary'
           AND escopo='global' AND chave='llm.model.fast'`,
      );
      expect(fastRow.rows[0]!.valor).toEqual({
        model: 'claude-haiku-4-5-20251001',
      });

      // Cleanup our seeded legacy rows so other tests aren't affected.
      await c.query(
        `DELETE FROM agent_facts
         WHERE tenant_id = 'primary'
           AND agent_id = 'primary'
           AND escopo = 'global'
           AND chave IN ('llm.model.main', 'llm.model.fast')`,
      );
    } finally {
      c.release();
    }
  });
});
